/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication4;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class booking extends javax.swing.JFrame {
Connection con;
    Statement st;
 PreparedStatement pstmt;
 ResultSet rs;
 CallableStatement cstmt;
    /**
     * Creates new form booking
     */
    public booking() {
       String dburl="jdbc:mysql://localhost:3306/ts";
    try 
    {
     Class.forName("com.mysql.jdbc.Driver").newInstance();	
     System.out.println("Driver Loaded Succesfully!");
     con = DriverManager.getConnection (dburl,"root","ssn");
     System.out.println("Connection Established!");      
     } 
     catch(ClassNotFoundException e) 
     {
		        System.out.println("Driver not loaded!");
     }
     catch(SQLException e) 
	{
		        System.out.println("Connection not established!");
	}
     catch(Exception e)
	{
			System.out.println("Instantiation exception.");
	}
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_frm = new javax.swing.JLabel();
        lb_to = new javax.swing.JLabel();
        lb_no = new javax.swing.JLabel();
        jcbfrm = new javax.swing.JComboBox();
        jcbto = new javax.swing.JComboBox();
        lb_type = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        lb_time = new javax.swing.JLabel();
        jcbtime = new javax.swing.JComboBox();
        qty = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        farep = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_apw = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_frm.setText("From:");

        lb_to.setText("To:");

        lb_no.setText("Quantity:");

        jcbfrm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbfrmActionPerformed(evt);
            }
        });

        lb_type.setText("Type:");

        r1.setText("One way");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });

        r2.setText("Two way");
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });

        lb_time.setText("Time:");

        qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyActionPerformed(evt);
            }
        });

        jButton3.setText("Find Trains");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Fare:");

        farep.setEditable(false);

        jButton1.setText("Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Clear");

        jButton4.setText("Show Fare");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setText("Password:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jcbfrm, 0, 160, Short.MAX_VALUE)
                                    .addComponent(jcbto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(lb_to, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_frm))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_time, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_no, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_type, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jButton3)
                        .addGap(0, 202, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jButton1)
                            .addComponent(jLabel1))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4)
                    .addComponent(jcbtime, 0, 162, Short.MAX_VALUE)
                    .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(r1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(r2))
                    .addComponent(farep, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(txt_apw))
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_time))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_no))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_type)
                            .addComponent(r1)
                            .addComponent(r2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(farep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_apw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_frm)
                            .addComponent(jcbfrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_to))
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbfrmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbfrmActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_jcbfrmActionPerformed

    private void qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            
            pstmt = con.prepareStatement("select arrtime from trainst where sname=?");
    Object j = jcbfrm.getSelectedItem();
    Object k = jcbto.getSelectedItem();
    String j1 = j.toString();
    String k1 = k.toString();
    if(j1.equals(k1))
           throw new Exception();
    pstmt.setString(1,j1);
    rs = pstmt.executeQuery();
    String str1 = "";
    int i=0;
    jcbtime.removeAllItems();
    while (rs.next())
    {
        
        str1 = rs.getString(1);
        jcbtime.addItem(str1);
            }   
        }
    catch(Exception ex)
    {
           JOptionPane.showMessageDialog(this,"Same station in from/to!");
    }// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        r2.setSelected(false);        // TODO add your handling code here:
    }//GEN-LAST:event_r1ActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
r1.setSelected(false);        // TODO add your handling code here:
    }//GEN-LAST:event_r2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String s=qty.getText();   
       Integer i=Integer.parseInt(s);
        if(i>10)
            JOptionPane.showMessageDialog(this,"Max # of tickets is 10!");
        else
        {
            try {
                
                Object f=jcbfrm.getSelectedItem();
                String fs22;
                String fs=f.toString();
                Object f2=jcbto.getSelectedItem();
                fs22=f2.toString();
                
                pstmt = con.prepareStatement("select sid from station where sname=?");
              pstmt.setString(1,fs);
              rs = pstmt.executeQuery();
              rs.next();
              String str1 = rs.getString(1);
              
             pstmt = con.prepareStatement("select sid from station where sname=?");
              pstmt.setString(1,fs22);
              rs = pstmt.executeQuery();
              rs.next();
              String str2 = rs.getString(1);
             
              Integer statfr=Integer.parseInt(str1);
              Integer statto=Integer.parseInt(str2);
              Integer res,tf;
              if(statfr>statto)
                  res=statfr-statto;
                    else
                        res=statto-statfr;
              res*=i;
              res*=5;
             if(r2.isSelected())
                 res*=2;
             String fp=res.toString();
                 farep.setText(fp);
            } 
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,"Not booked!");
            }
        } // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     try
     {
         String pass=txt_apw.getText();
         pstmt = con.prepareStatement("select uid from user where pword=?");
              pstmt.setString(1,pass);
              rs = pstmt.executeQuery();
              rs.next();
              String usid = rs.getString(1);
               Integer userid=Integer.parseInt(usid);
               
               Object g=jcbfrm.getSelectedItem();
                String gs22;
                String gs=g.toString();
                Object g2=jcbto.getSelectedItem();
                gs22=g2.toString();
                
                String radioText="";
                if(r2.isSelected())
                 radioText = r2.getText();    
                 if(r1.isSelected())
                 radioText = r1.getText();   
                String ff; 
                 ff=farep.getText();
                 
                 
                
               
              
         
       /*  pstmt=con.prepareStatement("insert into tkts values(?,?,?)");
            String s=a.toString();
            pstmt.setString(1,s);
            pstmt.setString(2,txt_nun.getText());
            pstmt.setString(3,txt_npw.getText());
            pstmt.execute();
            JOptionPane.showMessageDialog(this,"Registered Succesfully");*/
     }catch(SQLException ex)
    {
         JOptionPane.showMessageDialog(this,"Username already taken! Please enter new username!");
     // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField farep;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox jcbfrm;
    private javax.swing.JComboBox jcbtime;
    private javax.swing.JComboBox jcbto;
    private javax.swing.JLabel lb_frm;
    private javax.swing.JLabel lb_no;
    private javax.swing.JLabel lb_time;
    private javax.swing.JLabel lb_to;
    private javax.swing.JLabel lb_type;
    private javax.swing.JTextField qty;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JPasswordField txt_apw;
    // End of variables declaration//GEN-END:variables
}
