/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication4;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class sch extends javax.swing.JFrame {

    /**
     * Creates new form sch
     */
      Connection con;
    Statement st;
 PreparedStatement pstmt;
 ResultSet rs;
 CallableStatement cstmt;
    public sch() {
        String dburl="jdbc:mysql://localhost:3306/ts";
    try 
    {
     Class.forName("com.mysql.jdbc.Driver").newInstance();	
     System.out.println("Driver Loaded Succesfully!");
     con = DriverManager.getConnection (dburl,"root","ssn");
     System.out.println("Connection Established!");      
     } 
     catch(ClassNotFoundException e) 
     {
		        System.out.println("Driver not loaded!");
     }
     catch(SQLException e) 
	{
		        System.out.println("Connection not established!");
	}
     catch(Exception e)
	{
			System.out.println("Instantiation exception.");
	}
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_fsch = new javax.swing.JButton();
        bt_back2 = new javax.swing.JButton();
        lb_tim = new javax.swing.JLabel();
        lb_st = new javax.swing.JLabel();
        jcbsid = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_tim = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_fsch.setText("Find Schedule");
        bt_fsch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_fschActionPerformed(evt);
            }
        });

        bt_back2.setText("Back");
        bt_back2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_back2ActionPerformed(evt);
            }
        });

        lb_tim.setText("Timings");

        lb_st.setText("Station:");

        jcbsid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbsidActionPerformed(evt);
            }
        });

        txt_tim.setColumns(20);
        txt_tim.setRows(5);
        jScrollPane3.setViewportView(txt_tim);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_st)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_tim)
                    .addComponent(jcbsid, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bt_fsch)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(bt_back2)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_st)
                    .addComponent(jcbsid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_fsch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_tim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_back2)
                .addGap(170, 170, 170))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_fschActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_fschActionPerformed
        try {
            pstmt = con.prepareStatement("select arrtime from trainst where sname=?");
            Object j = jcbsid.getSelectedItem();
            String j1 = j.toString();
            pstmt.setString(1,j1);
            rs = pstmt.executeQuery();
            String str1 = "";
            int i=0;
            while (rs.next())
            {
                 i++;
                if(i==1)
                {
                str1 = rs.getString(1);
                }
                else
                {
                 str1=str1.concat("\n").concat(rs.getString(1));    
                }   
                txt_tim.setText(str1);
            }
            JOptionPane.showMessageDialog(this, "Station Found");
        } catch (SQLException ex2) {
            JOptionPane.showMessageDialog(this, "Invalid Station Entered !!");
        }     // TODO add your handling code here:
    }//GEN-LAST:event_bt_fschActionPerformed

    private void jcbsidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbsidActionPerformed
        //jcbsid.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"india", "pakistan"}));
    }//GEN-LAST:event_jcbsidActionPerformed

    private void bt_back2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_back2ActionPerformed
            this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_bt_back2ActionPerformed

    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_back2;
    private javax.swing.JButton bt_fsch;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox jcbsid;
    private javax.swing.JLabel lb_st;
    private javax.swing.JLabel lb_tim;
    private javax.swing.JTextArea txt_tim;
    // End of variables declaration//GEN-END:variables
}
